name: 🚀 Docker CI/CD for FastAPI

on:
  push:
    branches: [main]  # Trigger when pushing to main branch

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v3

    - name: 🐳 Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: 🔐 Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 🏗️ Build Docker Image
      run: |
        docker build -t srisabreesh/diabetes-api:latest .

    - name: 📤 Push Docker Image
      run: |
        docker push srisabreesh/diabetes-api:latest
